-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.get_user_by_email(useremail text)
--  RETURNS SETOF users
--  LANGUAGE plpgsql
-- AS $function$
-- BEGIN
--     RETURN query
--         SELECT * FROM users WHERE email = useremail;
-- END
-- $function$;
