-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.get_roles()
--  RETURNS SETOF roles
--  LANGUAGE plpgsql
-- AS $function$
-- BEGIN
--     return query select * from public.roles;
-- END
-- $function$;
